# ___
# Atividade: Variáveis aleatórias discretas
___

## Aula 09

**Propiedades da Esperança**

* $E(X + d)$ = $E(X)$ + $d$
* $E(cX)$ = $cE(X)$ 

* $E(cX + d)$ = $cE(X)$ + $d$

**Propiedades da Variância**

* $Var(X + d)$ = $Var(X)$ 
* $Var(cX)$ = $c^2Var(X)$ 
* $Var(cX + d)$ = $c^2Var(X)$

<div id="indice"></div>

## Índice

- [Corretora de Seguros](#corretora-de-seguros)
    - [Exercício 1](#ex1)
    - [Exercício 2](#ex2)
    - [Exercício 3](#ex3)
    - [Exercício 4](#ex4)
    - [Exercício 5](#ex5)
    - [Exercício 6](#ex6)


In [1]:
import numpy as np
import random
import pandas as pd

___

<div id="corretora-de-seguros"></div>

## Corretora de Seguros

Uma corretora de seguros paga uma comissão de R\\$50,00 a cada novo seguro que um corretor vende. A probabilidade de um cliente adquirir o seguro é de 0,20. 

1. Descreva como pode se comportar a comissão se um corretor ao abordar 2 clientes de maneira independente um do outro.
1. Qual a probabilidade de um corretor ganhar apenas R\\$50,00?

Vamos considerar os eventos:

- $S_i$: o cliente $i$ compra o seguro;
- $N_i = S_i^C$: o cliente $i$ não compra o seguro.

Pelo enunciado sabemos que:

- $P(S_i) = 0.2$
- $P(N_i) = P(S_i^C) = 1 - P(S_i) = 0.8$

Listando todas as possíveis combinações de eventos, temos:

Cliente 1 | Cliente 2 | Probabilidade           | Valor da comissão
--------- | --------- | ----------------------- | -----------------
$N_1$     | $N_2$     | $P(N_1)P(N_2)$ = $0.64$ | 0
$N_1$     | $S_2$     | $P(N_1)P(S_2)$ = $0.16$ | 50
$S_1$     | $N_2$     | $P(S_1)P(N_2)$ = $0.16$ | 50
$S_1$     | $S_2$     | $P(S_1)P(S_2)$ = $0.04$ | 100

Estamos interessados no valor da comissão de um corretor. Para isso, vamos definir a variável aleatória:

- $C$: valor da comissão do corretor.

Assim, o item 2 pode ser interpretado como: qual é o valor de $P(C=50)$?

Consultando a tabela calculada acima, vemos que $P(C=50) = 0.16 + 0.16 = 0.32$.

<div id="ex1"></div>

### EXERCÍCIO 1

Calcule o valor esperado e a variância da variável $C$.

*Resposta esperada para esperança e variância respectivamente: 20.0 reais ; 800.0 reais^2*

In [18]:
# ESCREVA SEU CÓDIGO AQUI

# Esperança -> é uma medida de tendência central - Valor médio

lista_P = [0.64,0.32,0.04]
lista_x = [0,50,100]

E = 0
for i in range(len(lista_P)):
    termo = lista_x[i]*lista_P[i]
    E += termo
    
print(f"O valor esperado é {E}")

O valor esperado é 20.0


In [19]:
# Cálculo do Desvio Padrão


from math import sqrt

var = 0
for i in range(len(lista_P)):
    s = lista_P[i]*(lista_x[i] - E)**2
    var += s
    
Des_padrao = sqrt(var)

print(f"A variância é {var}")
print(f'O desvio padrão calculado é {Des_padrao:.4f}')

A variância é 800.0
O desvio padrão calculado é 28.2843


___
## Tomando uma decisão

Imagine que a corretora de seguros irá fornecer um aumento na comissão dos corretores. Entretanto, cada corretor poderá escolher uma das seguintes opções:

- **Opção 1:** Nova comissão será a comissão atual mais um fixo de R$ 20,00;
- **Opção 2:** Nova comissão será o dobro da atual comissão.

<br>

A ideia aqui é fazer uma escolha de qual delas é melhor para aumentar o ganho de um corretor. 

Para isso, resolva os exercícios a seguir para auxiliá-lo nessa escolha.

<div id="ex2"></div>

### EXERCÍCIO 2

Construa a distribuição de probabilidade para cada uma das opções.


ESCREVA SUA RESPOSTA AQUI

In [20]:
# ESCREVA SEU CÓDIGO AQUI

- **Opção 1:** Nova comissão será a comissão atual mais um fixo de R$ 20,00;


   Probabilidade        | Fixo de R\\$ 20,00 |
----------------------- | ------------------ | 
$P(N_1)P(N_2)$ = $0.64$ | 20                 |
$P(N_1)P(S_2)$+$P(S_1)P(N_2)$ = $0.32$ | 70  |              
$P(S_1)P(S_2)$ = $0.04$ | 120                | 


<div id="ex3"></div>

### Valor Esperado - Opção 1

Considerando as respectivas distribuições de probabilidades, calcule o valor esperado e a variância para cada opção. 

In [21]:
# Y = X + 20

lista_P = [0.64,0.32,0.04]
lista_y = [0+20,50+20,100+20]

Ey = 0
for i in range(len(lista_P)):
    termo = lista_y[i]*lista_P[i]
    Ey += termo
    
print(f"O valor esperado é {Ey}")

O valor esperado é 40.0


$E(Y)$ = $E(X)$ + $20$

<div id="ex5"></div>

### Variância - Opção 1

Baseado nas propriedades da variância (nos slides), calcule a variância para a nova comissão em cada uma das opções.

*Resposta esperada para variância opção 1 e 2 respectivamente: 800.0 reais^2 ; 3200.0 reais^2*

In [22]:
# Cálculo do Desvio Padrão

from math import sqrt

var_y = 0
for i in range(len(lista_P)):
    s = lista_P[i]*(lista_y[i] - Ey)**2
    var_y += s
    
Des_padrao_y = sqrt(var_y)

print(f"A variância é {var_y}")
print(f'O desvio padrão calculado é {Des_padrao_y:.4f}')

A variância é 800.0
O desvio padrão calculado é 28.2843


**Z = X + 20**

* $E(Y)$ = $E(X)$ + $20$

* $Var(Y)$ = $Var(X)$

# PROF


   Probabilidade        | Fixo de R\\$ 20,00 | Dobro da comissão atual
----------------------- | ------------------ | -----------------------
$P(N_1)P(N_2)$ = $0.64$ | 20                 | 0
$P(N_1)P(S_2)$+$P(S_1)P(N_2)$ = $0.32$ | 70                 | 100
$P(S_1)P(S_2)$ = $0.04$ | 120                | 200


<div id="ex4"></div>

### Valor Esperado - Opção 2

Baseado nas propriedades da esperança (nos slides), calcule o valor esperado para a nova comissão em cada uma das opções.

*Resposta esperada para esperança opção 1 e 2 respectivamente: 40.0 reais ; 40.0 reais*

- **Opção 2:** Nova comissão será o dobro da atual comissão.


   Probabilidade        | Dobro da comissão atual
----------------------- | -----------------------
$P(N_1)P(N_2)$ = $0.64$ | 0
$P(N_1)P(S_2)$+$P(S_1)P(N_2)$ = $0.32$ | 100
$P(S_1)P(S_2)$ = $0.04$ | 200


In [23]:
# Z = 2X

lista_P = [0.64,0.32,0.04]
lista_z = [0,100,200]

Ez = 0
for i in range(len(lista_P)):
    termo = lista_z[i]*lista_P[i]
    Ez += termo
    
print(f"O valor esperado é {Ez}")

O valor esperado é 40.0


$E(Y)$ = 2$E(X)$

<div id="ex5"></div>

### Variância - Opção 2

Baseado nas propriedades da variância (nos slides), calcule a variância para a nova comissão em cada uma das opções.

*Resposta esperada para variância opção 1 e 2 respectivamente: 800.0 reais^2 ; 3200.0 reais^2*

In [25]:
var_z = 0

for i in range(len(lista_P)):
    s = lista_P[i]*(lista_z[i]-Ez)**2
    var_z += s 
    
Des_padrao_z = sqrt(var_z)

print(f"A variância é {var_z} para a nova comissão")
print(f'O desvio padrão calculado é {Des_padrao_z:.4f}')

A variância é 3200.0
O desvio padrão calculado é 56.5685


**Z = 2X**
* $E(Z)$ = $2$$E(X)$

* $Var(Z)$ = $(2^2)$$Var(X)$

<div id="ex6"></div>

### EXERCÍCIO 6

Baseado nos resultados acima, qual opção você recomendaria para um corretor?

ESCREVA SUA RESPOSTA AQUI

In [29]:
print(f"O valor esperado é {Ey} para a opção 1")
print(f"O valor esperado é {Ez} para a opção 2")

O valor esperado é 40.0 para a opção 1
O valor esperado é 40.0 para a opção 2


In [30]:
print(f"A variância é {var_y} para a opção 1")
print(f"A variância é {var_z} para a opção 2")

A variância é 800.0 para a opção 1
A variância é 3200.0 para a opção 2


# Referências

1. MONTGOMERY, D. et al. Estatística Aplicada e Probabilidade para Engenheiros. 6. ed. Seções 2.8 e 3.1
1. MAGALHÃES, M. et al. Noções de Probabilidade e Estatística. 7. ed. Seções 3.1 e definições 4.2 (p. 110) e 4.5 (p. 121)